export const actionType = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    USER_LOGOUT: 'USERS_LOGOUT_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    GET_CHAT_DATA: 'GET_CHAT_DATA',
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',
    LOGOUT: 'USERS_LOGOUT',
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    START_LOADING: 'START_LOADING',
    STOP_LOADING: 'STOP_LOADING',
    ALERT_MESSAGE: 'ALERT_MESSAGE',
    CLEAR_ALERT_MESSAGE: 'CLEAR_ALERT_MESSAGE'
  };
   