export const API_URL = "http://localhost:3001/"
export const USER_TOKEN = "USER_TOKEN"
export const USER_ID = "USER_ID"
export const USER_NAME = "USER_NAME"
export const USER_EMAIL = "USER_EMAIL"
export const INITIATE_CALL_EVENT = "INITIATE_CALL_EVENT"
export const SOCKET_URL = "http://localhost:3003/"